// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
//
// ─────────────────────────────────────────────────────────────────────────────
// IMPORTANT: Fill in your actual values from google-services.json
// You can find these values in Firebase Console → Project Settings → Your Apps
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // ─── Copy these values from your google-services.json ────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',           // client[0].api_key[0].current_key
    appId: 'YOUR_ANDROID_APP_ID',             // client[0].client_info.mobilesdk_app_id
    messagingSenderId: 'YOUR_SENDER_ID',      // project_info.project_number
    projectId: 'YOUR_PROJECT_ID',             // project_info.project_id
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  // ─── iOS values (from GoogleService-Info.plist if needed) ────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.homefixpro.homefixPro',
  );

  // ─── Web values (if you add web support later) ───────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}
